### ISSUE TITLE
TODO List 3R

### ISSUE THREAD

**Issue by 0999312** [0999312/umapyoi#4]
以下内容在12月18日前完成：
- [x] 模组宣传片
- [x] 三女神动画效果
- [x] 本地化（ENUS/ZHCN/ZHTW）
- [x] 获取因子，结束育成的设施（未起名、未设计）
***
以下内容在12月25日前完成：
- [x] HUD处理：技能和技能CD
- [x] 第一版技能集、因子集、支援效果集
- [x] 三女神因子继承细节处理
- [x] 训练设施GUI效果处理
- [x] 技能学习台GUI 技能效果说明显示。
- [x] 支援卡
- [x] 合成表
- [x] 模组初版发布
