### ISSUE TITLE
TODO List 5R

### ISSUE THREAD

**Issue by 0999312** [0999312/umapyoi#7]
模型：  
- [x] 长发优化——解决穿模问题/跑步时的摆动问题  
- [x] 尾巴优化——跑步跟随摆动  
- [x] 枢轴点匹配问题  
- [x] 更好的素体模型——统一标准  
  
***
可玩性：
- [x] 村民交易——提供部分物品获取方式   
- [x] 支援卡——基于数据包的可自定义物品  
- [x] 马娘属性上限突破——因子问题、属性曲线问题  
- [x] 添加进度——进度树安排  

***  
代码优化：
- [x] NBT物品优化处理  
- [ ] #10
- [ ] #9

***
其他：
- [ ] 开发者文档  
- [x] Patchouli教程  
*** 
放弃：添加原作音效——没有整理好的音效包，没有必要使用。

**Comment by 0999312** [comment]
技能系统：  
- [x] 行动力（Action Point）：使用技能时消耗的点数，行动力上限由智力决定。  
- [x] 被动技能：学习之后永久生效的技能；被动技能由事件系统实现，见下文。  
- [x] 技能上限：所有技能存在可学习上限；上限可以通过因子继承或部分SSR智力支援卡提升。  
- [ ] 技能扩充：更具有独特性的技能、更实用性的技能——范围效果，解除DEBUFF等实用性效果。  
- [x] 闸技能：对敌对生物/玩家等生效的减益技能。
***   
事件系统：  
需要以下自定义事件以解耦和方便附属开发。  
- [x] 技能事件：使用技能时 / 使用技能后 / 学习技能时 / 被动技能事件  
- [ ] 抽取物品事件：抽取马娘魂 / 支援卡时触发  
- [x] 因子继承事件：因子继承时触发  
- [x] 训练事件：训练结束后触发  
- [ ] 心情事件：心情变化时触发  
- [ ] 引退事件：引退登记时触发  
***  
马娘魂 / 支援卡 拆解：  
- [x] 马娘魂、马娘意志：结晶块——>训练设施升级 / 马娘抽取方块升级 / 抽取材料回收  
- [x] 支援卡：蹄铁——>训练设施升级 / 支援卡抽取方块升级 / 抽取材料回收  
***  
新增物品列表：  
- [x] 结晶块：灰 / 金 / 彩，拆解马娘魂得到。  
- [x] 蹄铁：灰 / 金 / 彩，拆解支援卡得到。  
- [ ] 运动鞋：铜 / 铁 / 金 / 彩，除铜可以直接使用铜锭合成外其他运动鞋需要使用蹄铁进行合成。  
- [x] 支援卡：支援卡物品，应当加急。 
- [x] 能量饮料：快速恢复行动力，即便在焦躁状态也可以恢复行动力。
- [ ] 其他食物：部分食物作为大餐可能会带来“发胖”效果，但必定提升至绝好调。 
***  
状态列表：
- [x] 焦躁状态：焦躁期间无法自然恢复行动力；若一直处于绝不调状态，再度受伤有可能会得到该状态；部分闸技能会直接赋予焦躁状态。  
- [ ] 发胖状态：发胖期间无法享受马娘带来的速度加成；部分食物作为大餐可能会带来“发胖”效果。  
***  
新增方块列表：  
- [x] 训练设施 ——> 训练员办公桌：由一级到五级，支援格子数逐级提升。三级解锁一次训练次数（训练前->出道后训练->训练完毕->引退），五级训练次数完全解锁（训练前->出道后训练->经典级->古典级->训练完毕->引退）。  
- [x] 训练回忆相册（支援卡蓝皮书）：抽取支援卡使用的方块。
- [x] 名称未定：抽取马娘时所使用的方块。
***
其他：
- [x] 三女神像调整：从抽马到只进行因子继承。  
- [x] 尾巴的随机摇摆效果  
- [x] 耳朵的随机晃动效果

**Comment by 0999312** [comment]
BUG: 
***
- [ ] 引退登记台：通过取放物品刷因子。

**Comment by 0999312** [comment]
该TODO List已废弃
